# Generated by Django 5.0.3 on 2024-03-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
    ]
