# Generated by Django 5.0.3 on 2024-03-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='last_search_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
