# Generated by Django 5.0.3 on 2024-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_cell_last_search_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='last_search_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
