# Generated by Django 5.0.3 on 2024-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_alter_cell_last_search_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='search_pending',
            field=models.BooleanField(default=False),
        ),
    ]
