# Generated by Django 5.0.3 on 2024-04-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_cell_search_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='last_search_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
