# Generated by Django 5.0.3 on 2024-04-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_alter_cell_last_search_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='name',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
