# Generated by Django 5.0.3 on 2024-04-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_cell_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='geom',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='geom',
            new_name='geometry',
        ),
    ]
