# Generated by Django 5.0.3 on 2024-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0008_rename_geom_area_geometry_rename_geom_cell_geometry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cell",
            name="last_search_timestamp",
        ),
        migrations.RemoveField(
            model_name="cell",
            name="search_pending",
        ),
        migrations.AddField(
            model_name="cell",
            name="search_started_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
