# Generated by Django 5.0.3 on 2024-04-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0009_remove_cell_last_search_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cell",
            name="search_finished_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
