services:
  db:
    image: postgis/postgis:latest
    volumes:
      - db-data:/var/lib/postgres/data/pgdata
    env_file:
      - .env

  redis:
    image: redis:alpine

  web:
    build: ./
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery:
    build: ./
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: celery -A flatscatalog worker -l INFO

  celery-beat:
    build: ./
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: celery -A flatscatalog beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler

volumes:
  db-data:
    driver: local