# Generated by Django 5.0.3 on 2024-03-31 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flat",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=256)),
                ("rooms_count", models.IntegerField()),
                ("total_area", models.FloatField()),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
