# Generated by Django 5.0.3 on 2024-03-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_flat_active_flat_created_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='location',
            new_name='geom',
        ),
    ]
