# Generated by Django 5.0.3 on 2024-04-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='external_id',
            field=models.IntegerField(unique=True),
        ),
    ]
