# Generated by Django 5.0.3 on 2024-04-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0006_remove_offer_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='last_search_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='search_pending',
            field=models.BooleanField(default=False),
        ),
    ]
