# Generated by Django 5.0.3 on 2024-04-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_offer_last_search_timestamp_offer_search_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatprice',
            old_name='value',
            new_name='price_rub',
        ),
    ]
