# Generated by Django 5.0.3 on 2024-04-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0008_rename_value_flatprice_price_rub'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatprice',
            name='price_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
