# Generated by Django 5.0.3 on 2024-04-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0009_flatprice_price_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='geom',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='geom',
            new_name='location',
        ),
        migrations.AddField(
            model_name='flat',
            name='build_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='external_id',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='external_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='floors_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='is_newbuilding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='total_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
