# Generated by Django 5.0.3 on 2024-04-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0010_rename_geom_flat_location_rename_geom_offer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flats.flat'),
        ),
    ]
