# Generated by Django 5.0.3 on 2024-04-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0011_offer_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='title',
        ),
    ]
