# Generated by Django 5.0.3 on 2024-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flats", "0012_remove_flat_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="last_search_timestamp",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="search_pending",
        ),
        migrations.AddField(
            model_name="offer",
            name="search_started_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
