# Generated by Django 5.0.3 on 2024-04-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0014_offer_search_finished_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='search_finished_timestamp',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='search_started_timestamp',
        ),
        migrations.AddField(
            model_name='offer',
            name='last_search_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='search_pending',
            field=models.BooleanField(default=False),
        ),
    ]
